// This file is auto-generated by @hey-api/openapi-ts

export const FirestoreTimestampSchema = {
  type: "object",
  properties: {
    _seconds: {
      type: "number",
    },
    _nanoseconds: {
      type: "number",
    },
  },
  required: ["_seconds", "_nanoseconds"],
} as const;

export const AuthUserSchema = {
  type: "object",
  properties: {
    uid: {
      type: "string",
    },
    email: {
      type: "string",
      nullable: true,
    },
    displayName: {
      type: "string",
    },
    role: {
      type: "string",
    },
    isAdmin: {
      type: "boolean",
    },
    status: {
      type: "string",
    },
    createdAt: {
      type: "object",
      properties: {
        _seconds: {
          type: "number",
        },
        _nanoseconds: {
          type: "number",
        },
      },
      required: ["_seconds", "_nanoseconds"],
    },
    updatedAt: {
      type: "object",
      properties: {
        _seconds: {
          type: "number",
        },
        _nanoseconds: {
          type: "number",
        },
      },
      required: ["_seconds", "_nanoseconds"],
    },
  },
  required: ["uid", "email"],
  additionalProperties: {
    nullable: true,
  },
} as const;

export const LoginRequestSchema = {
  type: "object",
  properties: {
    email: {
      type: "string",
      format: "email",
    },
    password: {
      type: "string",
      minLength: 1,
    },
  },
  required: ["email", "password"],
} as const;

export const LoginResponseDataSchema = {
  type: "object",
  properties: {
    accessToken: {
      type: "string",
    },
    refreshToken: {
      type: "string",
    },
    tokenType: {
      type: "string",
      enum: ["Bearer"],
    },
    expiresAt: {
      type: "string",
    },
    user: {
      type: "object",
      properties: {
        uid: {
          type: "string",
        },
        email: {
          type: "string",
          nullable: true,
        },
        displayName: {
          type: "string",
        },
        role: {
          type: "string",
        },
        isAdmin: {
          type: "boolean",
        },
        status: {
          type: "string",
        },
        createdAt: {
          type: "object",
          properties: {
            _seconds: {
              type: "number",
            },
            _nanoseconds: {
              type: "number",
            },
          },
          required: ["_seconds", "_nanoseconds"],
        },
        updatedAt: {
          type: "object",
          properties: {
            _seconds: {
              type: "number",
            },
            _nanoseconds: {
              type: "number",
            },
          },
          required: ["_seconds", "_nanoseconds"],
        },
      },
      required: ["uid", "email"],
      additionalProperties: {
        nullable: true,
      },
    },
  },
  required: ["accessToken", "refreshToken", "tokenType", "expiresAt", "user"],
} as const;

export const LoginResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "object",
      properties: {
        accessToken: {
          type: "string",
        },
        refreshToken: {
          type: "string",
        },
        tokenType: {
          type: "string",
          enum: ["Bearer"],
        },
        expiresAt: {
          type: "string",
        },
        user: {
          type: "object",
          properties: {
            uid: {
              type: "string",
            },
            email: {
              type: "string",
              nullable: true,
            },
            displayName: {
              type: "string",
            },
            role: {
              type: "string",
            },
            isAdmin: {
              type: "boolean",
            },
            status: {
              type: "string",
            },
            createdAt: {
              type: "object",
              properties: {
                _seconds: {
                  type: "number",
                },
                _nanoseconds: {
                  type: "number",
                },
              },
              required: ["_seconds", "_nanoseconds"],
            },
            updatedAt: {
              type: "object",
              properties: {
                _seconds: {
                  type: "number",
                },
                _nanoseconds: {
                  type: "number",
                },
              },
              required: ["_seconds", "_nanoseconds"],
            },
          },
          required: ["uid", "email"],
          additionalProperties: {
            nullable: true,
          },
        },
      },
      required: [
        "accessToken",
        "refreshToken",
        "tokenType",
        "expiresAt",
        "user",
      ],
    },
  },
  required: ["message", "data"],
} as const;

export const LogoutResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "object",
      properties: {
        success: {
          type: "boolean",
          enum: [true],
        },
      },
      required: ["success"],
    },
  },
  required: ["message", "data"],
} as const;

export const ApiErrorResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    error: {
      type: "string",
    },
  },
  required: ["message", "error"],
} as const;

export const CreateJobRequestSchema = {
  type: "object",
  properties: {
    title: {
      type: "string",
    },
    department: {
      type: "string",
      enum: [
        "ENGINEERING",
        "MARKETING",
        "SALES",
        "HR",
        "DESIGN",
        "PRODUCT",
        "OTHER",
      ],
    },
    jobType: {
      type: "string",
      enum: ["FULL_TIME", "PART_TIME", "CONTRACT", "INTERNSHIP"],
    },
    location: {
      type: "string",
    },
    description: {
      type: "string",
    },
    responsibilities: {
      type: "array",
      items: {
        type: "string",
      },
    },
    requirements: {
      type: "array",
      items: {
        type: "string",
      },
    },
    niceToHave: {
      type: "array",
      items: {
        type: "string",
      },
    },
    minSalary: {
      type: "number",
    },
    maxSalary: {
      type: "number",
    },
    status: {
      type: "string",
      enum: ["DRAFT", "OPEN", "CLOSED"],
    },
  },
  required: [
    "title",
    "department",
    "jobType",
    "location",
    "description",
    "responsibilities",
    "requirements",
    "niceToHave",
  ],
} as const;

export const UpdateJobRequestSchema = {
  type: "object",
  properties: {
    title: {
      type: "string",
    },
    department: {
      type: "string",
      enum: [
        "ENGINEERING",
        "MARKETING",
        "SALES",
        "HR",
        "DESIGN",
        "PRODUCT",
        "OTHER",
      ],
    },
    jobType: {
      type: "string",
      enum: ["FULL_TIME", "PART_TIME", "CONTRACT", "INTERNSHIP"],
    },
    location: {
      type: "string",
    },
    description: {
      type: "string",
    },
    responsibilities: {
      type: "array",
      items: {
        type: "string",
      },
    },
    requirements: {
      type: "array",
      items: {
        type: "string",
      },
    },
    niceToHave: {
      type: "array",
      items: {
        type: "string",
      },
    },
    minSalary: {
      type: "number",
    },
    maxSalary: {
      type: "number",
    },
    status: {
      type: "string",
      enum: ["DRAFT", "OPEN", "CLOSED"],
    },
  },
} as const;

export const JobResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "object",
      properties: {
        id: {
          type: "string",
        },
        title: {
          type: "string",
        },
        department: {
          type: "string",
          enum: [
            "ENGINEERING",
            "MARKETING",
            "SALES",
            "HR",
            "DESIGN",
            "PRODUCT",
            "OTHER",
          ],
        },
        jobType: {
          type: "string",
          enum: ["FULL_TIME", "PART_TIME", "CONTRACT", "INTERNSHIP"],
        },
        location: {
          type: "string",
        },
        description: {
          type: "string",
        },
        responsibilities: {
          type: "array",
          items: {
            type: "string",
          },
        },
        requirements: {
          type: "array",
          items: {
            type: "string",
          },
        },
        niceToHave: {
          type: "array",
          items: {
            type: "string",
          },
        },
        minSalary: {
          type: "number",
        },
        maxSalary: {
          type: "number",
        },
        status: {
          type: "string",
          enum: ["DRAFT", "OPEN", "CLOSED"],
        },
        createdAt: {
          type: "string",
        },
        updatedAt: {
          type: "string",
        },
      },
      required: [
        "id",
        "title",
        "department",
        "jobType",
        "location",
        "description",
        "responsibilities",
        "requirements",
        "niceToHave",
        "status",
        "createdAt",
        "updatedAt",
      ],
    },
  },
  required: ["message", "data"],
} as const;

export const JobsListResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string",
          },
          title: {
            type: "string",
          },
          department: {
            type: "string",
            enum: [
              "ENGINEERING",
              "MARKETING",
              "SALES",
              "HR",
              "DESIGN",
              "PRODUCT",
              "OTHER",
            ],
          },
          jobType: {
            type: "string",
            enum: ["FULL_TIME", "PART_TIME", "CONTRACT", "INTERNSHIP"],
          },
          location: {
            type: "string",
          },
          description: {
            type: "string",
          },
          responsibilities: {
            type: "array",
            items: {
              type: "string",
            },
          },
          requirements: {
            type: "array",
            items: {
              type: "string",
            },
          },
          niceToHave: {
            type: "array",
            items: {
              type: "string",
            },
          },
          minSalary: {
            type: "number",
          },
          maxSalary: {
            type: "number",
          },
          status: {
            type: "string",
            enum: ["DRAFT", "OPEN", "CLOSED"],
          },
          createdAt: {
            type: "string",
          },
          updatedAt: {
            type: "string",
          },
        },
        required: [
          "id",
          "title",
          "department",
          "jobType",
          "location",
          "description",
          "responsibilities",
          "requirements",
          "niceToHave",
          "status",
          "createdAt",
          "updatedAt",
        ],
      },
    },
  },
  required: ["message", "data"],
} as const;

export const JobDeleteResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "object",
      properties: {
        id: {
          type: "string",
        },
      },
      required: ["id"],
    },
  },
  required: ["message", "data"],
} as const;

export const ApiErrorSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    error: {
      type: "string",
    },
  },
  required: ["message", "error"],
} as const;

export const CreateApplicantRequestSchema = {
  type: "object",
  properties: {
    jobId: {
      type: "string",
    },
    fullName: {
      type: "string",
    },
    email: {
      type: "string",
      format: "email",
    },
    phone: {
      type: "string",
    },
    resumeUrl: {
      type: "string",
      format: "uri",
    },
    portfolioUrl: {
      type: "string",
      format: "uri",
    },
    linkedinUrl: {
      type: "string",
      format: "uri",
    },
    coverLetter: {
      type: "string",
    },
    earliestStartDate: {
      type: "string",
    },
    assignedRecruiter: {
      type: "string",
    },
    assignedInterviewer: {
      type: "string",
    },
    interviewScheduledAt: {
      type: "string",
    },
    rejectionReason: {
      type: "string",
    },
    status: {
      type: "string",
      enum: [
        "NEW",
        "UNDER_REVIEW",
        "INTERVIEW_SCHEDULED",
        "ACCEPTED",
        "REJECTED",
      ],
    },
  },
  required: ["jobId", "fullName", "email", "phone", "resumeUrl", "coverLetter"],
} as const;

export const UpdateApplicantRequestSchema = {
  type: "object",
  properties: {
    jobId: {
      type: "string",
    },
    fullName: {
      type: "string",
    },
    email: {
      type: "string",
      format: "email",
    },
    phone: {
      type: "string",
    },
    resumeUrl: {
      type: "string",
      format: "uri",
    },
    portfolioUrl: {
      type: "string",
      format: "uri",
    },
    linkedinUrl: {
      type: "string",
      format: "uri",
    },
    coverLetter: {
      type: "string",
    },
    earliestStartDate: {
      type: "string",
    },
    assignedRecruiter: {
      type: "string",
    },
    assignedInterviewer: {
      type: "string",
    },
    interviewScheduledAt: {
      type: "string",
    },
    rejectionReason: {
      type: "string",
    },
    status: {
      type: "string",
      enum: [
        "NEW",
        "UNDER_REVIEW",
        "INTERVIEW_SCHEDULED",
        "ACCEPTED",
        "REJECTED",
      ],
    },
  },
} as const;

export const ApplicantResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "object",
      properties: {
        id: {
          type: "string",
        },
        jobId: {
          type: "string",
        },
        fullName: {
          type: "string",
        },
        email: {
          type: "string",
          format: "email",
        },
        phone: {
          type: "string",
        },
        resumeUrl: {
          type: "string",
          format: "uri",
        },
        portfolioUrl: {
          type: "string",
          format: "uri",
        },
        linkedinUrl: {
          type: "string",
          format: "uri",
        },
        coverLetter: {
          type: "string",
        },
        earliestStartDate: {
          type: "string",
        },
        status: {
          type: "string",
          enum: [
            "NEW",
            "UNDER_REVIEW",
            "INTERVIEW_SCHEDULED",
            "ACCEPTED",
            "REJECTED",
          ],
        },
        assignedRecruiter: {
          type: "string",
        },
        assignedInterviewer: {
          type: "string",
        },
        interviewScheduledAt: {
          type: "string",
        },
        rejectionReason: {
          type: "string",
        },
        createdAt: {
          type: "string",
        },
        updatedAt: {
          type: "string",
        },
      },
      required: [
        "id",
        "jobId",
        "fullName",
        "email",
        "phone",
        "resumeUrl",
        "coverLetter",
        "status",
        "createdAt",
        "updatedAt",
      ],
    },
  },
  required: ["message", "data"],
} as const;

export const ApplicantsListResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string",
          },
          jobId: {
            type: "string",
          },
          fullName: {
            type: "string",
          },
          email: {
            type: "string",
            format: "email",
          },
          phone: {
            type: "string",
          },
          resumeUrl: {
            type: "string",
            format: "uri",
          },
          portfolioUrl: {
            type: "string",
            format: "uri",
          },
          linkedinUrl: {
            type: "string",
            format: "uri",
          },
          coverLetter: {
            type: "string",
          },
          earliestStartDate: {
            type: "string",
          },
          status: {
            type: "string",
            enum: [
              "NEW",
              "UNDER_REVIEW",
              "INTERVIEW_SCHEDULED",
              "ACCEPTED",
              "REJECTED",
            ],
          },
          assignedRecruiter: {
            type: "string",
          },
          assignedInterviewer: {
            type: "string",
          },
          interviewScheduledAt: {
            type: "string",
          },
          rejectionReason: {
            type: "string",
          },
          createdAt: {
            type: "string",
          },
          updatedAt: {
            type: "string",
          },
        },
        required: [
          "id",
          "jobId",
          "fullName",
          "email",
          "phone",
          "resumeUrl",
          "coverLetter",
          "status",
          "createdAt",
          "updatedAt",
        ],
      },
    },
  },
  required: ["message", "data"],
} as const;

export const ApplicantDeleteResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "object",
      properties: {
        id: {
          type: "string",
        },
      },
      required: ["id"],
    },
  },
  required: ["message", "data"],
} as const;

export const RejectApplicantRequestSchema = {
  type: "object",
  properties: {
    rejectionReason: {
      type: "string",
    },
  },
} as const;

export const ScheduleInterviewRequestSchema = {
  type: "object",
  properties: {
    interviewScheduledAt: {
      type: "string",
    },
  },
  required: ["interviewScheduledAt"],
} as const;

export const AssignRecruiterRequestSchema = {
  type: "object",
  properties: {
    assignedRecruiter: {
      type: "string",
    },
  },
  required: ["assignedRecruiter"],
} as const;

export const AssignInterviewerRequestSchema = {
  type: "object",
  properties: {
    assignedInterviewer: {
      type: "string",
    },
  },
  required: ["assignedInterviewer"],
} as const;

export const HealthResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "object",
      properties: {
        ok: {
          type: "boolean",
          enum: [true],
        },
        uptimeSeconds: {
          type: "number",
        },
      },
      required: ["ok", "uptimeSeconds"],
    },
  },
  required: ["message", "data"],
} as const;

export const DashboardResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "object",
      properties: {
        totalJobs: {
          type: "number",
        },
        activeJobs: {
          type: "number",
        },
        totalApplicants: {
          type: "number",
        },
        newThisWeek: {
          type: "number",
        },
        recentApplications: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: {
                type: "string",
              },
              fullName: {
                type: "string",
              },
              email: {
                type: "string",
                format: "email",
              },
              status: {
                type: "string",
                enum: [
                  "NEW",
                  "UNDER_REVIEW",
                  "INTERVIEW_SCHEDULED",
                  "ACCEPTED",
                  "REJECTED",
                ],
              },
              position: {
                type: "string",
              },
              statusLabel: {
                type: "string",
              },
              appliedDate: {
                type: "string",
              },
            },
            required: [
              "id",
              "fullName",
              "email",
              "status",
              "position",
              "statusLabel",
              "appliedDate",
            ],
          },
        },
      },
      required: [
        "totalJobs",
        "activeJobs",
        "totalApplicants",
        "newThisWeek",
        "recentApplications",
      ],
    },
  },
  required: ["message", "data"],
} as const;

export const CreateTeamMemberRequestSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    position: {
      type: "string",
    },
    group: {
      type: "string",
      enum: ["leadership", "engineering-design", "product-operations"],
    },
    shortDescription: {
      type: "string",
    },
    detailedDescription: {
      type: "string",
    },
    profileImageUrl: {
      type: "string",
      format: "uri",
    },
    email: {
      type: "string",
      format: "email",
    },
    phone: {
      type: "string",
    },
    linkedinUrl: {
      type: "string",
      format: "uri",
    },
    twitterUrl: {
      type: "string",
      format: "uri",
    },
  },
  required: ["name", "position"],
} as const;

export const UpdateTeamMemberRequestSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    position: {
      type: "string",
    },
    group: {
      type: "string",
      enum: ["leadership", "engineering-design", "product-operations"],
    },
    shortDescription: {
      type: "string",
    },
    detailedDescription: {
      type: "string",
    },
    profileImageUrl: {
      type: "string",
      format: "uri",
    },
    email: {
      type: "string",
      format: "email",
    },
    phone: {
      type: "string",
    },
    linkedinUrl: {
      type: "string",
      format: "uri",
    },
    twitterUrl: {
      type: "string",
      format: "uri",
    },
  },
} as const;

export const TeamMemberResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "object",
      properties: {
        id: {
          type: "string",
        },
        name: {
          type: "string",
        },
        position: {
          type: "string",
        },
        group: {
          type: "string",
          enum: ["leadership", "engineering-design", "product-operations"],
        },
        shortDescription: {
          type: "string",
        },
        detailedDescription: {
          type: "string",
        },
        profileImageUrl: {
          type: "string",
          format: "uri",
        },
        email: {
          type: "string",
          format: "email",
        },
        phone: {
          type: "string",
        },
        linkedinUrl: {
          type: "string",
          format: "uri",
        },
        twitterUrl: {
          type: "string",
          format: "uri",
        },
        createdAt: {
          type: "string",
        },
        updatedAt: {
          type: "string",
        },
      },
      required: ["id", "name", "position", "createdAt", "updatedAt"],
    },
  },
  required: ["message", "data"],
} as const;

export const TeamMembersListResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string",
          },
          name: {
            type: "string",
          },
          position: {
            type: "string",
          },
          group: {
            type: "string",
            enum: ["leadership", "engineering-design", "product-operations"],
          },
          shortDescription: {
            type: "string",
          },
          detailedDescription: {
            type: "string",
          },
          profileImageUrl: {
            type: "string",
            format: "uri",
          },
          email: {
            type: "string",
            format: "email",
          },
          phone: {
            type: "string",
          },
          linkedinUrl: {
            type: "string",
            format: "uri",
          },
          twitterUrl: {
            type: "string",
            format: "uri",
          },
          createdAt: {
            type: "string",
          },
          updatedAt: {
            type: "string",
          },
        },
        required: ["id", "name", "position", "createdAt", "updatedAt"],
      },
    },
  },
  required: ["message", "data"],
} as const;

export const TeamMemberDeleteResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    data: {
      type: "object",
      properties: {
        id: {
          type: "string",
        },
      },
      required: ["id"],
    },
  },
  required: ["message", "data"],
} as const;
