// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  DeleteApiApplicantsByIdData,
  DeleteApiApplicantsByIdErrors,
  DeleteApiApplicantsByIdResponses,
  DeleteApiJobsByIdData,
  DeleteApiJobsByIdErrors,
  DeleteApiJobsByIdResponses,
  GetApiApplicantsByIdData,
  GetApiApplicantsByIdErrors,
  GetApiApplicantsByIdResponses,
  GetApiApplicantsData,
  GetApiApplicantsErrors,
  GetApiApplicantsResponses,
  GetApiAuthMeData,
  GetApiAuthMeErrors,
  GetApiAuthMeResponses,
  GetApiDashboardData,
  GetApiDashboardErrors,
  GetApiDashboardResponses,
  GetApiHealthData,
  GetApiHealthResponses,
  GetApiJobsByIdData,
  GetApiJobsByIdErrors,
  GetApiJobsByIdResponses,
  GetApiJobsByJobIdApplicantsData,
  GetApiJobsByJobIdApplicantsErrors,
  GetApiJobsByJobIdApplicantsResponses,
  GetApiJobsData,
  GetApiJobsErrors,
  GetApiJobsResponses,
  PatchApiApplicantsByIdData,
  PatchApiApplicantsByIdErrors,
  PatchApiApplicantsByIdResponses,
  PatchApiJobsByIdData,
  PatchApiJobsByIdErrors,
  PatchApiJobsByIdResponses,
  PostApiApplicantsByIdAssignInterviewerData,
  PostApiApplicantsByIdAssignInterviewerErrors,
  PostApiApplicantsByIdAssignInterviewerResponses,
  PostApiApplicantsByIdAssignRecruiterData,
  PostApiApplicantsByIdAssignRecruiterErrors,
  PostApiApplicantsByIdAssignRecruiterResponses,
  PostApiApplicantsByIdNextStageData,
  PostApiApplicantsByIdNextStageErrors,
  PostApiApplicantsByIdNextStageResponses,
  PostApiApplicantsByIdRejectData,
  PostApiApplicantsByIdRejectErrors,
  PostApiApplicantsByIdRejectResponses,
  PostApiApplicantsByIdScheduleInterviewData,
  PostApiApplicantsByIdScheduleInterviewErrors,
  PostApiApplicantsByIdScheduleInterviewResponses,
  PostApiApplicantsData,
  PostApiApplicantsErrors,
  PostApiApplicantsResponses,
  PostApiAuthLoginData,
  PostApiAuthLoginErrors,
  PostApiAuthLoginResponses,
  PostApiAuthLogoutData,
  PostApiAuthLogoutErrors,
  PostApiAuthLogoutResponses,
  PostApiJobsData,
  PostApiJobsErrors,
  PostApiJobsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Authenticate a user with email and password
 */
export const postApiAuthLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiAuthLoginResponses,
    PostApiAuthLoginErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get the currently authenticated user
 */
export const getApiAuthMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiAuthMeResponses,
    GetApiAuthMeErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/me",
    ...options,
  });

/**
 * Logout the authenticated user
 */
export const postApiAuthLogout = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiAuthLogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiAuthLogoutResponses,
    PostApiAuthLogoutErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/logout",
    ...options,
  });

/**
 * List jobs
 */
export const getApiJobs = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiJobsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiJobsResponses,
    GetApiJobsErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/jobs",
    ...options,
  });

/**
 * Create job
 */
export const postApiJobs = <ThrowOnError extends boolean = false>(
  options: Options<PostApiJobsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiJobsResponses,
    PostApiJobsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/jobs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete job
 */
export const deleteApiJobsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiJobsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiJobsByIdResponses,
    DeleteApiJobsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/jobs/{id}",
    ...options,
  });

/**
 * Get job by id
 */
export const getApiJobsById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiJobsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiJobsByIdResponses,
    GetApiJobsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/jobs/{id}",
    ...options,
  });

/**
 * Update job
 */
export const patchApiJobsById = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiJobsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PatchApiJobsByIdResponses,
    PatchApiJobsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/jobs/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all applicants
 */
export const getApiApplicants = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiApplicantsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiApplicantsResponses,
    GetApiApplicantsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/applicants",
    ...options,
  });

/**
 * Submit a job application
 */
export const postApiApplicants = <ThrowOnError extends boolean = false>(
  options: Options<PostApiApplicantsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiApplicantsResponses,
    PostApiApplicantsErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/applicants",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete applicant
 */
export const deleteApiApplicantsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiApplicantsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiApplicantsByIdResponses,
    DeleteApiApplicantsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/applicants/{id}",
    ...options,
  });

/**
 * Get applicant by id
 */
export const getApiApplicantsById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiApplicantsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiApplicantsByIdResponses,
    GetApiApplicantsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/applicants/{id}",
    ...options,
  });

/**
 * Update applicant
 */
export const patchApiApplicantsById = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiApplicantsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PatchApiApplicantsByIdResponses,
    PatchApiApplicantsByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/applicants/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List applicants for a job
 */
export const getApiJobsByJobIdApplicants = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiJobsByJobIdApplicantsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiJobsByJobIdApplicantsResponses,
    GetApiJobsByJobIdApplicantsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/jobs/{jobId}/applicants",
    ...options,
  });

/**
 * Reject an applicant
 */
export const postApiApplicantsByIdReject = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiApplicantsByIdRejectData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiApplicantsByIdRejectResponses,
    PostApiApplicantsByIdRejectErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/applicants/{id}/reject",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Schedule an interview for an applicant
 */
export const postApiApplicantsByIdScheduleInterview = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiApplicantsByIdScheduleInterviewData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiApplicantsByIdScheduleInterviewResponses,
    PostApiApplicantsByIdScheduleInterviewErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/applicants/{id}/schedule-interview",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Assign a recruiter to an applicant
 */
export const postApiApplicantsByIdAssignRecruiter = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiApplicantsByIdAssignRecruiterData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiApplicantsByIdAssignRecruiterResponses,
    PostApiApplicantsByIdAssignRecruiterErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/applicants/{id}/assign-recruiter",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Assign an interviewer to an applicant
 */
export const postApiApplicantsByIdAssignInterviewer = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiApplicantsByIdAssignInterviewerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiApplicantsByIdAssignInterviewerResponses,
    PostApiApplicantsByIdAssignInterviewerErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/applicants/{id}/assign-interviewer",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Move applicant to the next stage
 */
export const postApiApplicantsByIdNextStage = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiApplicantsByIdNextStageData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiApplicantsByIdNextStageResponses,
    PostApiApplicantsByIdNextStageErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/applicants/{id}/next-stage",
    ...options,
  });

/**
 * Health check
 */
export const getApiHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiHealthData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiHealthResponses, unknown, ThrowOnError>(
    {
      responseType: "json",
      url: "/api/health",
      ...options,
    },
  );

/**
 * Get dashboard overview
 */
export const getApiDashboard = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiDashboardData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiDashboardResponses,
    GetApiDashboardErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/dashboard",
    ...options,
  });
