// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://localhost:8080" | (string & {});
};

export type FirestoreTimestamp = {
  _seconds: number;
  _nanoseconds: number;
};

export type AuthUser = {
  uid: string;
  email: string | null;
  displayName?: string;
  role?: string;
  isAdmin?: boolean;
  status?: string;
  createdAt?: {
    _seconds: number;
    _nanoseconds: number;
  };
  updatedAt?: {
    _seconds: number;
    _nanoseconds: number;
  };
  [key: string]: unknown;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type LoginResponseData = {
  accessToken: string;
  refreshToken: string;
  tokenType: "Bearer";
  expiresAt: string;
  user: {
    uid: string;
    email: string | null;
    displayName?: string;
    role?: string;
    isAdmin?: boolean;
    status?: string;
    createdAt?: {
      _seconds: number;
      _nanoseconds: number;
    };
    updatedAt?: {
      _seconds: number;
      _nanoseconds: number;
    };
    [key: string]: unknown;
  };
};

export type LoginResponse = {
  message: string;
  data: {
    accessToken: string;
    refreshToken: string;
    tokenType: "Bearer";
    expiresAt: string;
    user: {
      uid: string;
      email: string | null;
      displayName?: string;
      role?: string;
      isAdmin?: boolean;
      status?: string;
      createdAt?: {
        _seconds: number;
        _nanoseconds: number;
      };
      updatedAt?: {
        _seconds: number;
        _nanoseconds: number;
      };
      [key: string]: unknown;
    };
  };
};

export type LogoutResponse = {
  message: string;
  data: {
    success: true;
  };
};

export type ApiErrorResponse = {
  message: string;
  error: string;
};

export type CreateJobRequest = {
  title: string;
  department:
    | "ENGINEERING"
    | "MARKETING"
    | "SALES"
    | "HR"
    | "DESIGN"
    | "PRODUCT"
    | "OTHER";
  jobType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP";
  location: string;
  description: string;
  responsibilities: Array<string>;
  requirements: Array<string>;
  niceToHave: Array<string>;
  minSalary?: number;
  maxSalary?: number;
  status?: "DRAFT" | "OPEN" | "CLOSED";
};

export type UpdateJobRequest = {
  title?: string;
  department?:
    | "ENGINEERING"
    | "MARKETING"
    | "SALES"
    | "HR"
    | "DESIGN"
    | "PRODUCT"
    | "OTHER";
  jobType?: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP";
  location?: string;
  description?: string;
  responsibilities?: Array<string>;
  requirements?: Array<string>;
  niceToHave?: Array<string>;
  minSalary?: number;
  maxSalary?: number;
  status?: "DRAFT" | "OPEN" | "CLOSED";
};

export type JobResponse = {
  message: string;
  data: {
    id: string;
    title: string;
    department:
      | "ENGINEERING"
      | "MARKETING"
      | "SALES"
      | "HR"
      | "DESIGN"
      | "PRODUCT"
      | "OTHER";
    jobType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP";
    location: string;
    description: string;
    responsibilities: Array<string>;
    requirements: Array<string>;
    niceToHave: Array<string>;
    minSalary?: number;
    maxSalary?: number;
    status: "DRAFT" | "OPEN" | "CLOSED";
    createdAt: string;
    updatedAt: string;
  };
};

export type JobsListResponse = {
  message: string;
  data: Array<{
    id: string;
    title: string;
    department:
      | "ENGINEERING"
      | "MARKETING"
      | "SALES"
      | "HR"
      | "DESIGN"
      | "PRODUCT"
      | "OTHER";
    jobType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP";
    location: string;
    description: string;
    responsibilities: Array<string>;
    requirements: Array<string>;
    niceToHave: Array<string>;
    minSalary?: number;
    maxSalary?: number;
    status: "DRAFT" | "OPEN" | "CLOSED";
    createdAt: string;
    updatedAt: string;
  }>;
};

export type JobDeleteResponse = {
  message: string;
  data: {
    id: string;
  };
};

export type ApiError = {
  message: string;
  error: string;
};

export type CreateApplicantRequest = {
  jobId: string;
  fullName: string;
  email: string;
  phone: string;
  resumeUrl: string;
  portfolioUrl?: string;
  linkedinUrl?: string;
  coverLetter: string;
  earliestStartDate?: string;
  assignedRecruiter?: string;
  assignedInterviewer?: string;
  interviewScheduledAt?: string;
  rejectionReason?: string;
  status?:
    | "NEW"
    | "UNDER_REVIEW"
    | "INTERVIEW_SCHEDULED"
    | "ACCEPTED"
    | "REJECTED";
};

export type UpdateApplicantRequest = {
  jobId?: string;
  fullName?: string;
  email?: string;
  phone?: string;
  resumeUrl?: string;
  portfolioUrl?: string;
  linkedinUrl?: string;
  coverLetter?: string;
  earliestStartDate?: string;
  assignedRecruiter?: string;
  assignedInterviewer?: string;
  interviewScheduledAt?: string;
  rejectionReason?: string;
  status?:
    | "NEW"
    | "UNDER_REVIEW"
    | "INTERVIEW_SCHEDULED"
    | "ACCEPTED"
    | "REJECTED";
};

export type ApplicantResponse = {
  message: string;
  data: {
    id: string;
    jobId: string;
    fullName: string;
    email: string;
    phone: string;
    resumeUrl: string;
    portfolioUrl?: string;
    linkedinUrl?: string;
    coverLetter: string;
    earliestStartDate?: string;
    status:
      | "NEW"
      | "UNDER_REVIEW"
      | "INTERVIEW_SCHEDULED"
      | "ACCEPTED"
      | "REJECTED";
    assignedRecruiter?: string;
    assignedInterviewer?: string;
    interviewScheduledAt?: string;
    rejectionReason?: string;
    createdAt: string;
    updatedAt: string;
  };
};

export type ApplicantsListResponse = {
  message: string;
  data: Array<{
    id: string;
    jobId: string;
    fullName: string;
    email: string;
    phone: string;
    resumeUrl: string;
    portfolioUrl?: string;
    linkedinUrl?: string;
    coverLetter: string;
    earliestStartDate?: string;
    status:
      | "NEW"
      | "UNDER_REVIEW"
      | "INTERVIEW_SCHEDULED"
      | "ACCEPTED"
      | "REJECTED";
    assignedRecruiter?: string;
    assignedInterviewer?: string;
    interviewScheduledAt?: string;
    rejectionReason?: string;
    createdAt: string;
    updatedAt: string;
  }>;
};

export type ApplicantDeleteResponse = {
  message: string;
  data: {
    id: string;
  };
};

export type RejectApplicantRequest = {
  rejectionReason?: string;
};

export type ScheduleInterviewRequest = {
  interviewScheduledAt: string;
};

export type AssignRecruiterRequest = {
  assignedRecruiter: string;
};

export type AssignInterviewerRequest = {
  assignedInterviewer: string;
};

export type HealthResponse = {
  message: string;
  data: {
    ok: true;
    uptimeSeconds: number;
  };
};

export type DashboardResponse = {
  message: string;
  data: {
    totalJobs: number;
    activeJobs: number;
    totalApplicants: number;
    newThisWeek: number;
    recentApplications: Array<{
      id: string;
      fullName: string;
      email: string;
      status:
        | "NEW"
        | "UNDER_REVIEW"
        | "INTERVIEW_SCHEDULED"
        | "ACCEPTED"
        | "REJECTED";
      position: string;
      statusLabel: string;
      appliedDate: string;
    }>;
  };
};

export type FileUploadRequest = {
  file: Blob | File;
  name?: string;
  folder?: string;
};

export type FileUploadResponse = {
  message: string;
  data: {
    fileName: string;
    url: string;
    publicId: string;
    size: number;
    mimeType: string;
  };
};

export type ResumeUploadRequest = {
  resume: Blob | File;
  name?: string;
  folder?: string;
};

export type ResumeUploadResponse = {
  message: string;
  data: {
    fileName: string;
    url: string;
    publicId: string;
    size: number;
    mimeType: string;
  };
};

export type PostApiAuthLoginData = {
  body: {
    email: string;
    password: string;
  };
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type PostApiAuthLoginErrors = {
  /**
   * Validation error
   */
  400: {
    message: string;
    error: string;
  };
  /**
   * Authentication failed
   */
  401: {
    message: string;
    error: string;
  };
};

export type PostApiAuthLoginError =
  PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
  /**
   * Login successful
   */
  200: {
    message: string;
    data: {
      accessToken: string;
      refreshToken: string;
      tokenType: "Bearer";
      expiresAt: string;
      user: {
        uid: string;
        email: string | null;
        displayName?: string;
        role?: string;
        isAdmin?: boolean;
        status?: string;
        createdAt?: {
          _seconds: number;
          _nanoseconds: number;
        };
        updatedAt?: {
          _seconds: number;
          _nanoseconds: number;
        };
        [key: string]: unknown;
      };
    };
  };
};

export type PostApiAuthLoginResponse =
  PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type GetApiAuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/me";
};

export type GetApiAuthMeErrors = {
  /**
   * Unauthorized
   */
  401: {
    message: string;
    error: string;
  };
};

export type GetApiAuthMeError = GetApiAuthMeErrors[keyof GetApiAuthMeErrors];

export type GetApiAuthMeResponses = {
  /**
   * Authenticated user fetched successfully
   */
  200: {
    message: string;
    data: {
      uid: string;
      email: string | null;
      claims: {
        [key: string]: unknown;
      };
    };
  };
};

export type GetApiAuthMeResponse =
  GetApiAuthMeResponses[keyof GetApiAuthMeResponses];

export type PostApiAuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/logout";
};

export type PostApiAuthLogoutErrors = {
  /**
   * Unauthorized
   */
  401: {
    message: string;
    error: string;
  };
};

export type PostApiAuthLogoutError =
  PostApiAuthLogoutErrors[keyof PostApiAuthLogoutErrors];

export type PostApiAuthLogoutResponses = {
  /**
   * Logout successful
   */
  200: {
    message: string;
    data: {
      success: true;
    };
  };
};

export type PostApiAuthLogoutResponse =
  PostApiAuthLogoutResponses[keyof PostApiAuthLogoutResponses];

export type GetApiJobsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/jobs";
};

export type GetApiJobsErrors = {
  /**
   * Failed to fetch jobs
   */
  500: {
    message: string;
    error: string;
  };
};

export type GetApiJobsError = GetApiJobsErrors[keyof GetApiJobsErrors];

export type GetApiJobsResponses = {
  /**
   * Jobs fetched successfully
   */
  200: {
    message: string;
    data: Array<{
      id: string;
      title: string;
      department:
        | "ENGINEERING"
        | "MARKETING"
        | "SALES"
        | "HR"
        | "DESIGN"
        | "PRODUCT"
        | "OTHER";
      jobType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP";
      location: string;
      description: string;
      responsibilities: Array<string>;
      requirements: Array<string>;
      niceToHave: Array<string>;
      minSalary?: number;
      maxSalary?: number;
      status: "DRAFT" | "OPEN" | "CLOSED";
      createdAt: string;
      updatedAt: string;
    }>;
  };
};

export type GetApiJobsResponse = GetApiJobsResponses[keyof GetApiJobsResponses];

export type PostApiJobsData = {
  body: {
    title: string;
    department:
      | "ENGINEERING"
      | "MARKETING"
      | "SALES"
      | "HR"
      | "DESIGN"
      | "PRODUCT"
      | "OTHER";
    jobType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP";
    location: string;
    description: string;
    responsibilities: Array<string>;
    requirements: Array<string>;
    niceToHave: Array<string>;
    minSalary?: number;
    maxSalary?: number;
    status?: "DRAFT" | "OPEN" | "CLOSED";
  };
  path?: never;
  query?: never;
  url: "/api/jobs";
};

export type PostApiJobsErrors = {
  /**
   * Validation error
   */
  400: {
    message: string;
    error: string;
  };
  /**
   * Unauthorized
   */
  401: {
    message: string;
    error: string;
  };
};

export type PostApiJobsError = PostApiJobsErrors[keyof PostApiJobsErrors];

export type PostApiJobsResponses = {
  /**
   * Job created successfully
   */
  201: {
    message: string;
    data: {
      id: string;
      title: string;
      department:
        | "ENGINEERING"
        | "MARKETING"
        | "SALES"
        | "HR"
        | "DESIGN"
        | "PRODUCT"
        | "OTHER";
      jobType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP";
      location: string;
      description: string;
      responsibilities: Array<string>;
      requirements: Array<string>;
      niceToHave: Array<string>;
      minSalary?: number;
      maxSalary?: number;
      status: "DRAFT" | "OPEN" | "CLOSED";
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type PostApiJobsResponse =
  PostApiJobsResponses[keyof PostApiJobsResponses];

export type DeleteApiJobsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/jobs/{id}";
};

export type DeleteApiJobsByIdErrors = {
  /**
   * Job not found
   */
  404: {
    message: string;
    error: string;
  };
};

export type DeleteApiJobsByIdError =
  DeleteApiJobsByIdErrors[keyof DeleteApiJobsByIdErrors];

export type DeleteApiJobsByIdResponses = {
  /**
   * Job deleted successfully
   */
  200: {
    message: string;
    data: {
      id: string;
    };
  };
};

export type DeleteApiJobsByIdResponse =
  DeleteApiJobsByIdResponses[keyof DeleteApiJobsByIdResponses];

export type GetApiJobsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/jobs/{id}";
};

export type GetApiJobsByIdErrors = {
  /**
   * Job not found
   */
  404: {
    message: string;
    error: string;
  };
};

export type GetApiJobsByIdError =
  GetApiJobsByIdErrors[keyof GetApiJobsByIdErrors];

export type GetApiJobsByIdResponses = {
  /**
   * Job fetched successfully
   */
  200: {
    message: string;
    data: {
      id: string;
      title: string;
      department:
        | "ENGINEERING"
        | "MARKETING"
        | "SALES"
        | "HR"
        | "DESIGN"
        | "PRODUCT"
        | "OTHER";
      jobType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP";
      location: string;
      description: string;
      responsibilities: Array<string>;
      requirements: Array<string>;
      niceToHave: Array<string>;
      minSalary?: number;
      maxSalary?: number;
      status: "DRAFT" | "OPEN" | "CLOSED";
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type GetApiJobsByIdResponse =
  GetApiJobsByIdResponses[keyof GetApiJobsByIdResponses];

export type PatchApiJobsByIdData = {
  body: {
    title?: string;
    department?:
      | "ENGINEERING"
      | "MARKETING"
      | "SALES"
      | "HR"
      | "DESIGN"
      | "PRODUCT"
      | "OTHER";
    jobType?: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP";
    location?: string;
    description?: string;
    responsibilities?: Array<string>;
    requirements?: Array<string>;
    niceToHave?: Array<string>;
    minSalary?: number;
    maxSalary?: number;
    status?: "DRAFT" | "OPEN" | "CLOSED";
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/jobs/{id}";
};

export type PatchApiJobsByIdErrors = {
  /**
   * Job not found
   */
  404: {
    message: string;
    error: string;
  };
};

export type PatchApiJobsByIdError =
  PatchApiJobsByIdErrors[keyof PatchApiJobsByIdErrors];

export type PatchApiJobsByIdResponses = {
  /**
   * Job updated successfully
   */
  200: {
    message: string;
    data: {
      id: string;
      title: string;
      department:
        | "ENGINEERING"
        | "MARKETING"
        | "SALES"
        | "HR"
        | "DESIGN"
        | "PRODUCT"
        | "OTHER";
      jobType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP";
      location: string;
      description: string;
      responsibilities: Array<string>;
      requirements: Array<string>;
      niceToHave: Array<string>;
      minSalary?: number;
      maxSalary?: number;
      status: "DRAFT" | "OPEN" | "CLOSED";
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type PatchApiJobsByIdResponse =
  PatchApiJobsByIdResponses[keyof PatchApiJobsByIdResponses];

export type GetApiApplicantsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/applicants";
};

export type GetApiApplicantsErrors = {
  /**
   * Unauthorized
   */
  401: {
    message: string;
    error: string;
  };
};

export type GetApiApplicantsError =
  GetApiApplicantsErrors[keyof GetApiApplicantsErrors];

export type GetApiApplicantsResponses = {
  /**
   * Applicants fetched successfully
   */
  200: {
    message: string;
    data: Array<{
      id: string;
      jobId: string;
      fullName: string;
      email: string;
      phone: string;
      resumeUrl: string;
      portfolioUrl?: string;
      linkedinUrl?: string;
      coverLetter: string;
      earliestStartDate?: string;
      status:
        | "NEW"
        | "UNDER_REVIEW"
        | "INTERVIEW_SCHEDULED"
        | "ACCEPTED"
        | "REJECTED";
      assignedRecruiter?: string;
      assignedInterviewer?: string;
      interviewScheduledAt?: string;
      rejectionReason?: string;
      createdAt: string;
      updatedAt: string;
    }>;
  };
};

export type GetApiApplicantsResponse =
  GetApiApplicantsResponses[keyof GetApiApplicantsResponses];

export type PostApiApplicantsData = {
  body: {
    jobId: string;
    fullName: string;
    email: string;
    phone: string;
    resumeUrl: string;
    portfolioUrl?: string;
    linkedinUrl?: string;
    coverLetter: string;
    earliestStartDate?: string;
    assignedRecruiter?: string;
    assignedInterviewer?: string;
    interviewScheduledAt?: string;
    rejectionReason?: string;
    status?:
      | "NEW"
      | "UNDER_REVIEW"
      | "INTERVIEW_SCHEDULED"
      | "ACCEPTED"
      | "REJECTED";
  };
  path?: never;
  query?: never;
  url: "/api/applicants";
};

export type PostApiApplicantsErrors = {
  /**
   * Validation error
   */
  400: {
    message: string;
    error: string;
  };
};

export type PostApiApplicantsError =
  PostApiApplicantsErrors[keyof PostApiApplicantsErrors];

export type PostApiApplicantsResponses = {
  /**
   * Application submitted successfully
   */
  201: {
    message: string;
    data: {
      id: string;
      jobId: string;
      fullName: string;
      email: string;
      phone: string;
      resumeUrl: string;
      portfolioUrl?: string;
      linkedinUrl?: string;
      coverLetter: string;
      earliestStartDate?: string;
      status:
        | "NEW"
        | "UNDER_REVIEW"
        | "INTERVIEW_SCHEDULED"
        | "ACCEPTED"
        | "REJECTED";
      assignedRecruiter?: string;
      assignedInterviewer?: string;
      interviewScheduledAt?: string;
      rejectionReason?: string;
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type PostApiApplicantsResponse =
  PostApiApplicantsResponses[keyof PostApiApplicantsResponses];

export type DeleteApiApplicantsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/applicants/{id}";
};

export type DeleteApiApplicantsByIdErrors = {
  /**
   * Applicant not found
   */
  404: {
    message: string;
    error: string;
  };
};

export type DeleteApiApplicantsByIdError =
  DeleteApiApplicantsByIdErrors[keyof DeleteApiApplicantsByIdErrors];

export type DeleteApiApplicantsByIdResponses = {
  /**
   * Applicant deleted successfully
   */
  200: {
    message: string;
    data: {
      id: string;
    };
  };
};

export type DeleteApiApplicantsByIdResponse =
  DeleteApiApplicantsByIdResponses[keyof DeleteApiApplicantsByIdResponses];

export type GetApiApplicantsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/applicants/{id}";
};

export type GetApiApplicantsByIdErrors = {
  /**
   * Applicant not found
   */
  404: {
    message: string;
    error: string;
  };
};

export type GetApiApplicantsByIdError =
  GetApiApplicantsByIdErrors[keyof GetApiApplicantsByIdErrors];

export type GetApiApplicantsByIdResponses = {
  /**
   * Applicant fetched successfully
   */
  200: {
    message: string;
    data: {
      id: string;
      jobId: string;
      fullName: string;
      email: string;
      phone: string;
      resumeUrl: string;
      portfolioUrl?: string;
      linkedinUrl?: string;
      coverLetter: string;
      earliestStartDate?: string;
      status:
        | "NEW"
        | "UNDER_REVIEW"
        | "INTERVIEW_SCHEDULED"
        | "ACCEPTED"
        | "REJECTED";
      assignedRecruiter?: string;
      assignedInterviewer?: string;
      interviewScheduledAt?: string;
      rejectionReason?: string;
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type GetApiApplicantsByIdResponse =
  GetApiApplicantsByIdResponses[keyof GetApiApplicantsByIdResponses];

export type PatchApiApplicantsByIdData = {
  body: {
    jobId?: string;
    fullName?: string;
    email?: string;
    phone?: string;
    resumeUrl?: string;
    portfolioUrl?: string;
    linkedinUrl?: string;
    coverLetter?: string;
    earliestStartDate?: string;
    assignedRecruiter?: string;
    assignedInterviewer?: string;
    interviewScheduledAt?: string;
    rejectionReason?: string;
    status?:
      | "NEW"
      | "UNDER_REVIEW"
      | "INTERVIEW_SCHEDULED"
      | "ACCEPTED"
      | "REJECTED";
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/applicants/{id}";
};

export type PatchApiApplicantsByIdErrors = {
  /**
   * Applicant not found
   */
  404: {
    message: string;
    error: string;
  };
};

export type PatchApiApplicantsByIdError =
  PatchApiApplicantsByIdErrors[keyof PatchApiApplicantsByIdErrors];

export type PatchApiApplicantsByIdResponses = {
  /**
   * Applicant updated successfully
   */
  200: {
    message: string;
    data: {
      id: string;
      jobId: string;
      fullName: string;
      email: string;
      phone: string;
      resumeUrl: string;
      portfolioUrl?: string;
      linkedinUrl?: string;
      coverLetter: string;
      earliestStartDate?: string;
      status:
        | "NEW"
        | "UNDER_REVIEW"
        | "INTERVIEW_SCHEDULED"
        | "ACCEPTED"
        | "REJECTED";
      assignedRecruiter?: string;
      assignedInterviewer?: string;
      interviewScheduledAt?: string;
      rejectionReason?: string;
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type PatchApiApplicantsByIdResponse =
  PatchApiApplicantsByIdResponses[keyof PatchApiApplicantsByIdResponses];

export type GetApiJobsByJobIdApplicantsData = {
  body?: never;
  path: {
    jobId: string;
  };
  query?: never;
  url: "/api/jobs/{jobId}/applicants";
};

export type GetApiJobsByJobIdApplicantsErrors = {
  /**
   * Unauthorized
   */
  401: {
    message: string;
    error: string;
  };
};

export type GetApiJobsByJobIdApplicantsError =
  GetApiJobsByJobIdApplicantsErrors[keyof GetApiJobsByJobIdApplicantsErrors];

export type GetApiJobsByJobIdApplicantsResponses = {
  /**
   * Applicants fetched successfully
   */
  200: {
    message: string;
    data: Array<{
      id: string;
      jobId: string;
      fullName: string;
      email: string;
      phone: string;
      resumeUrl: string;
      portfolioUrl?: string;
      linkedinUrl?: string;
      coverLetter: string;
      earliestStartDate?: string;
      status:
        | "NEW"
        | "UNDER_REVIEW"
        | "INTERVIEW_SCHEDULED"
        | "ACCEPTED"
        | "REJECTED";
      assignedRecruiter?: string;
      assignedInterviewer?: string;
      interviewScheduledAt?: string;
      rejectionReason?: string;
      createdAt: string;
      updatedAt: string;
    }>;
  };
};

export type GetApiJobsByJobIdApplicantsResponse =
  GetApiJobsByJobIdApplicantsResponses[keyof GetApiJobsByJobIdApplicantsResponses];

export type PostApiApplicantsByIdRejectData = {
  body?: {
    rejectionReason?: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/applicants/{id}/reject";
};

export type PostApiApplicantsByIdRejectErrors = {
  /**
   * Applicant not found
   */
  404: {
    message: string;
    error: string;
  };
};

export type PostApiApplicantsByIdRejectError =
  PostApiApplicantsByIdRejectErrors[keyof PostApiApplicantsByIdRejectErrors];

export type PostApiApplicantsByIdRejectResponses = {
  /**
   * Applicant rejected
   */
  200: {
    message: string;
    data: {
      id: string;
      jobId: string;
      fullName: string;
      email: string;
      phone: string;
      resumeUrl: string;
      portfolioUrl?: string;
      linkedinUrl?: string;
      coverLetter: string;
      earliestStartDate?: string;
      status:
        | "NEW"
        | "UNDER_REVIEW"
        | "INTERVIEW_SCHEDULED"
        | "ACCEPTED"
        | "REJECTED";
      assignedRecruiter?: string;
      assignedInterviewer?: string;
      interviewScheduledAt?: string;
      rejectionReason?: string;
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type PostApiApplicantsByIdRejectResponse =
  PostApiApplicantsByIdRejectResponses[keyof PostApiApplicantsByIdRejectResponses];

export type PostApiApplicantsByIdScheduleInterviewData = {
  body: {
    interviewScheduledAt: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/applicants/{id}/schedule-interview";
};

export type PostApiApplicantsByIdScheduleInterviewErrors = {
  /**
   * Applicant not found
   */
  404: {
    message: string;
    error: string;
  };
};

export type PostApiApplicantsByIdScheduleInterviewError =
  PostApiApplicantsByIdScheduleInterviewErrors[keyof PostApiApplicantsByIdScheduleInterviewErrors];

export type PostApiApplicantsByIdScheduleInterviewResponses = {
  /**
   * Interview scheduled
   */
  200: {
    message: string;
    data: {
      id: string;
      jobId: string;
      fullName: string;
      email: string;
      phone: string;
      resumeUrl: string;
      portfolioUrl?: string;
      linkedinUrl?: string;
      coverLetter: string;
      earliestStartDate?: string;
      status:
        | "NEW"
        | "UNDER_REVIEW"
        | "INTERVIEW_SCHEDULED"
        | "ACCEPTED"
        | "REJECTED";
      assignedRecruiter?: string;
      assignedInterviewer?: string;
      interviewScheduledAt?: string;
      rejectionReason?: string;
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type PostApiApplicantsByIdScheduleInterviewResponse =
  PostApiApplicantsByIdScheduleInterviewResponses[keyof PostApiApplicantsByIdScheduleInterviewResponses];

export type PostApiApplicantsByIdAssignRecruiterData = {
  body: {
    assignedRecruiter: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/applicants/{id}/assign-recruiter";
};

export type PostApiApplicantsByIdAssignRecruiterErrors = {
  /**
   * Applicant not found
   */
  404: {
    message: string;
    error: string;
  };
};

export type PostApiApplicantsByIdAssignRecruiterError =
  PostApiApplicantsByIdAssignRecruiterErrors[keyof PostApiApplicantsByIdAssignRecruiterErrors];

export type PostApiApplicantsByIdAssignRecruiterResponses = {
  /**
   * Recruiter assigned
   */
  200: {
    message: string;
    data: {
      id: string;
      jobId: string;
      fullName: string;
      email: string;
      phone: string;
      resumeUrl: string;
      portfolioUrl?: string;
      linkedinUrl?: string;
      coverLetter: string;
      earliestStartDate?: string;
      status:
        | "NEW"
        | "UNDER_REVIEW"
        | "INTERVIEW_SCHEDULED"
        | "ACCEPTED"
        | "REJECTED";
      assignedRecruiter?: string;
      assignedInterviewer?: string;
      interviewScheduledAt?: string;
      rejectionReason?: string;
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type PostApiApplicantsByIdAssignRecruiterResponse =
  PostApiApplicantsByIdAssignRecruiterResponses[keyof PostApiApplicantsByIdAssignRecruiterResponses];

export type PostApiApplicantsByIdAssignInterviewerData = {
  body: {
    assignedInterviewer: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/applicants/{id}/assign-interviewer";
};

export type PostApiApplicantsByIdAssignInterviewerErrors = {
  /**
   * Applicant not found
   */
  404: {
    message: string;
    error: string;
  };
};

export type PostApiApplicantsByIdAssignInterviewerError =
  PostApiApplicantsByIdAssignInterviewerErrors[keyof PostApiApplicantsByIdAssignInterviewerErrors];

export type PostApiApplicantsByIdAssignInterviewerResponses = {
  /**
   * Interviewer assigned
   */
  200: {
    message: string;
    data: {
      id: string;
      jobId: string;
      fullName: string;
      email: string;
      phone: string;
      resumeUrl: string;
      portfolioUrl?: string;
      linkedinUrl?: string;
      coverLetter: string;
      earliestStartDate?: string;
      status:
        | "NEW"
        | "UNDER_REVIEW"
        | "INTERVIEW_SCHEDULED"
        | "ACCEPTED"
        | "REJECTED";
      assignedRecruiter?: string;
      assignedInterviewer?: string;
      interviewScheduledAt?: string;
      rejectionReason?: string;
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type PostApiApplicantsByIdAssignInterviewerResponse =
  PostApiApplicantsByIdAssignInterviewerResponses[keyof PostApiApplicantsByIdAssignInterviewerResponses];

export type PostApiApplicantsByIdNextStageData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/applicants/{id}/next-stage";
};

export type PostApiApplicantsByIdNextStageErrors = {
  /**
   * Applicant not found
   */
  404: {
    message: string;
    error: string;
  };
};

export type PostApiApplicantsByIdNextStageError =
  PostApiApplicantsByIdNextStageErrors[keyof PostApiApplicantsByIdNextStageErrors];

export type PostApiApplicantsByIdNextStageResponses = {
  /**
   * Applicant moved to next stage
   */
  200: {
    message: string;
    data: {
      id: string;
      jobId: string;
      fullName: string;
      email: string;
      phone: string;
      resumeUrl: string;
      portfolioUrl?: string;
      linkedinUrl?: string;
      coverLetter: string;
      earliestStartDate?: string;
      status:
        | "NEW"
        | "UNDER_REVIEW"
        | "INTERVIEW_SCHEDULED"
        | "ACCEPTED"
        | "REJECTED";
      assignedRecruiter?: string;
      assignedInterviewer?: string;
      interviewScheduledAt?: string;
      rejectionReason?: string;
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type PostApiApplicantsByIdNextStageResponse =
  PostApiApplicantsByIdNextStageResponses[keyof PostApiApplicantsByIdNextStageResponses];

export type GetApiHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/health";
};

export type GetApiHealthResponses = {
  /**
   * Service is healthy
   */
  200: {
    message: string;
    data: {
      ok: true;
      uptimeSeconds: number;
    };
  };
};

export type GetApiHealthResponse =
  GetApiHealthResponses[keyof GetApiHealthResponses];

export type GetApiDashboardData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/dashboard";
};

export type GetApiDashboardErrors = {
  /**
   * Unauthorized
   */
  401: {
    message: string;
    error: string;
  };
};

export type GetApiDashboardError =
  GetApiDashboardErrors[keyof GetApiDashboardErrors];

export type GetApiDashboardResponses = {
  /**
   * Dashboard data fetched successfully
   */
  200: {
    message: string;
    data: {
      totalJobs: number;
      activeJobs: number;
      totalApplicants: number;
      newThisWeek: number;
      recentApplications: Array<{
        id: string;
        fullName: string;
        email: string;
        status:
          | "NEW"
          | "UNDER_REVIEW"
          | "INTERVIEW_SCHEDULED"
          | "ACCEPTED"
          | "REJECTED";
        position: string;
        statusLabel: string;
        appliedDate: string;
      }>;
    };
  };
};

export type GetApiDashboardResponse =
  GetApiDashboardResponses[keyof GetApiDashboardResponses];

export type PostApiUploadsFileData = {
  body: {
    file: Blob | File;
    name?: string;
    folder?: string;
  };
  path?: never;
  query?: never;
  url: "/api/uploads/file";
};

export type PostApiUploadsFileErrors = {
  /**
   * Invalid upload request
   */
  400: {
    message: string;
    error: string;
  };
};

export type PostApiUploadsFileError =
  PostApiUploadsFileErrors[keyof PostApiUploadsFileErrors];

export type PostApiUploadsFileResponses = {
  /**
   * File uploaded successfully
   */
  201: {
    message: string;
    data: {
      fileName: string;
      url: string;
      publicId: string;
      size: number;
      mimeType: string;
    };
  };
};

export type PostApiUploadsFileResponse =
  PostApiUploadsFileResponses[keyof PostApiUploadsFileResponses];

export type PostApiUploadsResumeData = {
  body: {
    resume: Blob | File;
    name?: string;
    folder?: string;
  };
  path?: never;
  query?: never;
  url: "/api/uploads/resume";
};

export type PostApiUploadsResumeErrors = {
  /**
   * Invalid upload request
   */
  400: {
    message: string;
    error: string;
  };
};

export type PostApiUploadsResumeError =
  PostApiUploadsResumeErrors[keyof PostApiUploadsResumeErrors];

export type PostApiUploadsResumeResponses = {
  /**
   * Resume uploaded successfully
   */
  201: {
    message: string;
    data: {
      fileName: string;
      url: string;
      publicId: string;
      size: number;
      mimeType: string;
    };
  };
};

export type PostApiUploadsResumeResponse =
  PostApiUploadsResumeResponses[keyof PostApiUploadsResumeResponses];
