// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/favicon.ico": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/api/uploads/resume": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/sw.js": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/case-studies": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/career": {
    params: {};
  };
  "/career/:jobId": {
    params: {
      "jobId": string;
    };
  };
  "/career/:jobId/success": {
    params: {
      "jobId": string;
    };
  };
  "/terms": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/page/:slug": {
    params: {
      "slug": string;
    };
  };
  "/console": {
    params: {};
  };
  "/console/jobs": {
    params: {};
  };
  "/console/jobs/new": {
    params: {};
  };
  "/console/jobs/:jobId/edit": {
    params: {
      "jobId": string;
    };
  };
  "/console/drafts": {
    params: {};
  };
  "/console/candidates": {
    params: {};
  };
  "/console/settings": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/favicon.ico" | "/api/health" | "/api/uploads/resume" | "/sitemap.xml" | "/sw.js" | "/services" | "/case-studies" | "/about" | "/contact" | "/health" | "/projects" | "/career" | "/career/:jobId" | "/career/:jobId/success" | "/terms" | "/privacy" | "/page/:slug" | "/console" | "/console/jobs" | "/console/jobs/new" | "/console/jobs/:jobId/edit" | "/console/drafts" | "/console/candidates" | "/console/settings" | "/login";
  };
  "routes/favicon[.]ico.tsx": {
    id: "routes/favicon[.]ico";
    page: "/favicon.ico";
  };
  "routes/api.health.tsx": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.uploads.resume.tsx": {
    id: "routes/api.uploads.resume";
    page: "/api/uploads/resume";
  };
  "routes/sitemap[.]xml.tsx": {
    id: "routes/sitemap[.]xml";
    page: "/sitemap.xml";
  };
  "routes/sw[.]js.tsx": {
    id: "routes/sw[.]js";
    page: "/sw.js";
  };
  "layouts/MainLayout.tsx": {
    id: "layouts/MainLayout";
    page: "/" | "/services" | "/case-studies" | "/about" | "/contact" | "/health" | "/projects" | "/career" | "/career/:jobId" | "/career/:jobId/success" | "/terms" | "/privacy" | "/page/:slug";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "routes/services/index.tsx": {
    id: "routes/services/index";
    page: "/services";
  };
  "routes/case-studies/index.tsx": {
    id: "routes/case-studies/index";
    page: "/case-studies";
  };
  "routes/about/index.tsx": {
    id: "routes/about/index";
    page: "/about";
  };
  "routes/contact/index.tsx": {
    id: "routes/contact/index";
    page: "/contact";
  };
  "routes/health/index.tsx": {
    id: "routes/health/index";
    page: "/health";
  };
  "routes/projects/index.tsx": {
    id: "routes/projects/index";
    page: "/projects";
  };
  "routes/career/index.tsx": {
    id: "routes/career/index";
    page: "/career";
  };
  "routes/career/$jobId.tsx": {
    id: "routes/career/$jobId";
    page: "/career/:jobId";
  };
  "routes/career/$jobId.success.tsx": {
    id: "routes/career/$jobId.success";
    page: "/career/:jobId/success";
  };
  "routes/terms/index.tsx": {
    id: "routes/terms/index";
    page: "/terms";
  };
  "routes/privacy/index.tsx": {
    id: "routes/privacy/index";
    page: "/privacy";
  };
  "routes/page/$slug.tsx": {
    id: "routes/page/$slug";
    page: "/page/:slug";
  };
  "layouts/ConsoleLayout.tsx": {
    id: "layouts/ConsoleLayout";
    page: "/console" | "/console/jobs" | "/console/jobs/new" | "/console/jobs/:jobId/edit" | "/console/drafts" | "/console/candidates" | "/console/settings";
  };
  "routes/console/index.tsx": {
    id: "routes/console/index";
    page: "/console";
  };
  "routes/console/jobs.tsx": {
    id: "routes/console/jobs";
    page: "/console/jobs";
  };
  "routes/console/jobs.new.tsx": {
    id: "routes/console/jobs.new";
    page: "/console/jobs/new";
  };
  "routes/console/jobs.edit.tsx": {
    id: "routes/console/jobs.edit";
    page: "/console/jobs/:jobId/edit";
  };
  "routes/console/drafts.tsx": {
    id: "routes/console/drafts";
    page: "/console/drafts";
  };
  "routes/console/candidates.tsx": {
    id: "routes/console/candidates";
    page: "/console/candidates";
  };
  "routes/console/settings.tsx": {
    id: "routes/console/settings";
    page: "/console/settings";
  };
  "routes/login/index.tsx": {
    id: "routes/login/index";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/favicon[.]ico": typeof import("./app/routes/favicon[.]ico.tsx");
  "routes/api.health": typeof import("./app/routes/api.health.tsx");
  "routes/api.uploads.resume": typeof import("./app/routes/api.uploads.resume.tsx");
  "routes/sitemap[.]xml": typeof import("./app/routes/sitemap[.]xml.tsx");
  "routes/sw[.]js": typeof import("./app/routes/sw[.]js.tsx");
  "layouts/MainLayout": typeof import("./app/layouts/MainLayout.tsx");
  "routes/home/index": typeof import("./app/routes/home/index.tsx");
  "routes/services/index": typeof import("./app/routes/services/index.tsx");
  "routes/case-studies/index": typeof import("./app/routes/case-studies/index.tsx");
  "routes/about/index": typeof import("./app/routes/about/index.tsx");
  "routes/contact/index": typeof import("./app/routes/contact/index.tsx");
  "routes/health/index": typeof import("./app/routes/health/index.tsx");
  "routes/projects/index": typeof import("./app/routes/projects/index.tsx");
  "routes/career/index": typeof import("./app/routes/career/index.tsx");
  "routes/career/$jobId": typeof import("./app/routes/career/$jobId.tsx");
  "routes/career/$jobId.success": typeof import("./app/routes/career/$jobId.success.tsx");
  "routes/terms/index": typeof import("./app/routes/terms/index.tsx");
  "routes/privacy/index": typeof import("./app/routes/privacy/index.tsx");
  "routes/page/$slug": typeof import("./app/routes/page/$slug.tsx");
  "layouts/ConsoleLayout": typeof import("./app/layouts/ConsoleLayout.tsx");
  "routes/console/index": typeof import("./app/routes/console/index.tsx");
  "routes/console/jobs": typeof import("./app/routes/console/jobs.tsx");
  "routes/console/jobs.new": typeof import("./app/routes/console/jobs.new.tsx");
  "routes/console/jobs.edit": typeof import("./app/routes/console/jobs.edit.tsx");
  "routes/console/drafts": typeof import("./app/routes/console/drafts.tsx");
  "routes/console/candidates": typeof import("./app/routes/console/candidates.tsx");
  "routes/console/settings": typeof import("./app/routes/console/settings.tsx");
  "routes/login/index": typeof import("./app/routes/login/index.tsx");
};