// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/favicon.ico": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/sw.js": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/case-studies": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/terms": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/page/:slug": {
    params: {
      "slug": string;
    };
  };
  "/console": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/favicon.ico" | "/sitemap.xml" | "/sw.js" | "/services" | "/case-studies" | "/about" | "/contact" | "/projects" | "/projects/:id" | "/terms" | "/privacy" | "/page/:slug" | "/console";
  };
  "routes/favicon[.]ico.tsx": {
    id: "routes/favicon[.]ico";
    page: "/favicon.ico";
  };
  "routes/sitemap[.]xml.tsx": {
    id: "routes/sitemap[.]xml";
    page: "/sitemap.xml";
  };
  "routes/sw[.]js.tsx": {
    id: "routes/sw[.]js";
    page: "/sw.js";
  };
  "layouts/MainLayout.tsx": {
    id: "layouts/MainLayout";
    page: "/" | "/services" | "/case-studies" | "/about" | "/contact" | "/projects" | "/projects/:id" | "/terms" | "/privacy" | "/page/:slug";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "routes/services/index.tsx": {
    id: "routes/services/index";
    page: "/services";
  };
  "routes/case-studies/index.tsx": {
    id: "routes/case-studies/index";
    page: "/case-studies";
  };
  "routes/about/index.tsx": {
    id: "routes/about/index";
    page: "/about";
  };
  "routes/contact/index.tsx": {
    id: "routes/contact/index";
    page: "/contact";
  };
  "routes/projects/index.tsx": {
    id: "routes/projects/index";
    page: "/projects";
  };
  "routes/projects/$id.tsx": {
    id: "routes/projects/$id";
    page: "/projects/:id";
  };
  "routes/terms/index.tsx": {
    id: "routes/terms/index";
    page: "/terms";
  };
  "routes/privacy/index.tsx": {
    id: "routes/privacy/index";
    page: "/privacy";
  };
  "routes/page/$slug.tsx": {
    id: "routes/page/$slug";
    page: "/page/:slug";
  };
  "layouts/ConsoleLayout.tsx": {
    id: "layouts/ConsoleLayout";
    page: "/console";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/favicon[.]ico": typeof import("./app/routes/favicon[.]ico.tsx");
  "routes/sitemap[.]xml": typeof import("./app/routes/sitemap[.]xml.tsx");
  "routes/sw[.]js": typeof import("./app/routes/sw[.]js.tsx");
  "layouts/MainLayout": typeof import("./app/layouts/MainLayout.tsx");
  "routes/home/index": typeof import("./app/routes/home/index.tsx");
  "routes/services/index": typeof import("./app/routes/services/index.tsx");
  "routes/case-studies/index": typeof import("./app/routes/case-studies/index.tsx");
  "routes/about/index": typeof import("./app/routes/about/index.tsx");
  "routes/contact/index": typeof import("./app/routes/contact/index.tsx");
  "routes/projects/index": typeof import("./app/routes/projects/index.tsx");
  "routes/projects/$id": typeof import("./app/routes/projects/$id.tsx");
  "routes/terms/index": typeof import("./app/routes/terms/index.tsx");
  "routes/privacy/index": typeof import("./app/routes/privacy/index.tsx");
  "routes/page/$slug": typeof import("./app/routes/page/$slug.tsx");
  "layouts/ConsoleLayout": typeof import("./app/layouts/ConsoleLayout.tsx");
};